name: Build and Release Electron App

on:
  workflow_dispatch:
    inputs:
      version-bump:
        description: 'Version bump type (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  build:
    defaults:
        run:
          working-directory: ./app
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '25.1.0' # Specify your Node.js version
        
      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npm run make # Adjust this command according to your build script

      - name: Zip Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          zip -r ./out/markdown-editor-linux-x64.zip ./out/markdown-editor-linux-x64
          ls -AR ./out

      - name: Zip Windows
        if: matrix.os == 'windows-latest'
        run: |
          tar -a -c -f ./out/markdown-editor-win32-x64.zip -C ./out/markdown-editor-win32-x64 .
          tree /F

      - name: Upload build artifacts Linux (deb)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}-deb
          path: ./out/make/deb/x64/markdown-editor_1.0.0_amd64.deb
            
      - name: Upload build artifacts Linux (rpm)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}-rpm
          path: ./out/make/rpm/x64/markdown-editor-1.0.0-1.x86_64.rpm

      - name: Upload build artifacts Linux (zip)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}-zip
          path: ./out/markdown-editor-linux-x64.zip

      - name: Upload build artifacts Windows (installer)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}-installer
          path: './out/make/squirrel.windows/x64/markdown-editor-1.0.0 Setup.exe'
            
      - name: Upload build artifacts Windows (portable)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}-portable
          path: './out/make/markdown-editor 1.0.0.exe'

      - name: Upload build artifacts Windows (zip)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}-zip
          path: ./out/markdown-editor-win32-x64.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts Linux
        uses: actions/download-artifact@v7
        with:
          name: app-ubuntu-latest-deb # Adjust this based on your output name
          path: ./artifacts # You can specify a directory to download into

      - name: Download build artifacts Windows
        uses: actions/download-artifact@v7
        with:
          name: app-windows-latest* # Adjust this based on your output name
          path: ./artifacts # You can specify a directory to download into
      
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Bump version
        id: bump_version
        run: |
          npm version ${{ github.event.inputs.version-bump }}
          echo "new_version=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.new_version }}
          files: |
            ./artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
